### **0. Importazione modulo**

Prima di tutto importo il modulo numpy

In [1]:
import numpy as np

### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

#### Primo esempio

In [2]:
#Lista con i primi 10 cubi

l = []
for i in range(1, 11):
    l.append(i**3)
print(l)

l1= [i**3 for i in range(1, 11)]
print(l1)

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]
[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


#### Secondo esempio

In [ ]:
#Lista con le prime 11 potenze di 2

l = []
for i in range(11):
    l.append(2**i)
print(l)

l1 = [2**i for i in range(11)]
print(l1)

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
11


#### Terzo esempio

In [9]:
#Lista con i soli numeri dispari tra 50 e 60

l = []
for i in range(50, 61):
    if(i % 2 != 0):
        l.append(i)
print(l)

l1 = [i for i in range(50, 60) if(i % 2 != 0)]
print(l1)

[51, 53, 55, 57, 59]
[51, 53, 55, 57, 59]


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [4]:
a = np.array([2, 3, 5, 7])
lungh = len(a)
lungh_2= a.size
print(lungh)
print(lungh_2)

#Mi aspetto che il dtype sia int, in quanto i numeri sono tutti interi
print(a.dtype)

b = [i for i in range(11) if((i == 2 or (i % 2 != 0 and all(i % x != 0 for x in range(2, i//2)))) and i != 1)]
print(b)

4
4
int64
[2, 3, 5, 7]


### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [5]:
l = []
for i in range(1, 11):
    l.append(i)
a = np.array(l)
print(a)
b = a[3:6]
print(b)
c = np.flip(a)
print(c)
print(a/c)

a1 = []
for i in range(1, 11):
    a1.append(i)
print(a1)
b1 = a[3:6]
print(b1)
c1 = a1.copy()
c1.reverse()
print(c1)
#print(a1/c1) #non supportato!! devo scorrerla tutta

rapporto = []
for i in range(len(a1)):
    rapporto.append(a1[i]/c1[i])
print(rapporto)

[ 1  2  3  4  5  6  7  8  9 10]
[4 5 6]
[10  9  8  7  6  5  4  3  2  1]
[ 0.1         0.22222222  0.375       0.57142857  0.83333333  1.2
  1.75        2.66666667  4.5        10.        ]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[4 5 6]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[0.1, 0.2222222222222222, 0.375, 0.5714285714285714, 0.8333333333333334, 1.2, 1.75, 2.6666666666666665, 4.5, 10.0]
